"jwt": 
  "expireduration": 2
  "secret": "i1ydX9RtHyuJTrw7frcu"
"pg": 
  "base": 
    "connmaxlifetime": 60
    "maxidleconn": 60
    "maxopenconn": 10
  "read": 
    "host": "192.168.1.5"
    "name": "fil_pool"
    "pass": "pass_2021"
    "port": "5435"
    "user": "fil_pool"
  "write": 
    "host": "192.168.1.5"
    "name": "fil_pool"
    "pass": "pass_2021"
    "port": "5435"
    "user": "fil_pool"
"redis": 
  "addr": "192.168.1.6:6379"
  "db": "9"
  "maxretries": 3
  "minidleconns": 5
  "pass": "redis_pass_2020"
  "poolsize": 10
"secretkey": 
  "aeskey": "x7rGlXIs2j19uC4c6RvNmoZbwkQfKSHD"
  "iv": "5ZgcWJxDvN71f3o6"
"sms":
  "regionId": "ap-northeast-1"
  "accessKeyId": "LTAI4FyvSPqcoFsZp4RdFzJ4"
  "accessKeySecret": "jaP2j3QfNWFTeiAsMVwxBHuYCH9n3X"
  "signName": "悦智"
  "templateCode": "SMS_139232384"